name: Issuebot

on:
  issues:
    types: [opened]

jobs:
  new_issue:
    name: Run Issuebot on new Issue
    runs-on: ubuntu-latest
    steps:
      - uses: wfjsw/actions-gocqhttp-issue-prefilter@master
